Created DecisionCriteriaUI and applicable DecisionCriteriaUITest
MetroCS/cs3250_practice pull request #138
Opened 2024-11-08 06:20 UTC by Jerem-Dough

This PR is addressing User-Story #115 

Contained are two new contributions, DecisionCriteriaUI.java and DecisionCriteriaUITest.java

The UI prompts users to enter the criteria they would like to be using. It requests them to then enter "done" when finished. After this, it will print the specific criterion they have entered, back to them. 

The associated testing file could be more robust, but it is a start.

2024-11-08 06:20 UTC, Jerem-Dough commented
I was the only group member involved with this specific PR.

2024-11-10 19:35 UTC, jody commented
> I was the only group member involved with this specific PR.

Without a co-contributor there is no peer assessment and review. Please ask a peer, in your team or not, to review this PR and add comments to this conversation.

2024-11-10 20:07 UTC, jody requested changes
1. The implementation class lacks basic javadoc-level comments. Maintainers need to know the intents.

2. The unit tests appear to address the utility methods within the class. Although these may satisfy for the use as a data class, there is no indication of testing (or how to test) the **primary functionality** of the class, which appears to involve "UI". You may want to investigate how to pass a Scanner, Writer, or OutputStream as a parameter. Then the test and the run-time can each pass different objects to satisfy the specific needs.

2024-11-11 04:37 UTC, Jerem-Dough commented
Understood, can I talk to you further about this assignment tomorrow before or after our lecture?

I'll also find a classmate to help with contributions during this time.

2024-11-12 00:00 UTC, jmaestas7 commented on decision_support/src/metrocs/DecisionCriteriaUI.java
> +                break;
Be careful in this case, where the input might never be "done." We also need to provide that option so the user knows what the breaking case is

2024-11-12 00:00 UTC, jmaestas7 commented on decision_support/src/metrocs/DecisionCriteriaUITest.java
> +
We are missing  test for the above comment. We need to verify via a unit test that the breaking phrase does work

2024-11-14 01:20 UTC, closed without merging